
package com.coverity.ws.v7;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConfigurationService", targetNamespace = "http://ws.coverity.com/v7")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConfigurationService {


    /**
     * 
     * @param message
     * @param usernames
     * @param subject
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notify", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.Notify")
    @ResponseWrapper(localName = "notifyResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.NotifyResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/notifyRequest", output = "http://ws.coverity.com/v7/ConfigurationService/notifyResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/notify/Fault/CovRemoteServiceException")
    })
    public List<String> notify(
        @WebParam(name = "usernames", targetNamespace = "")
        List<String> usernames,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "message", targetNamespace = "")
        String message)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v7.AttributeDefinitionDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttributes", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAttributes")
    @ResponseWrapper(localName = "getAttributesResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAttributesResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getAttributesRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getAttributesResponse")
    public List<AttributeDefinitionDataObj> getAttributes();

    /**
     * 
     * @param attributeDefinitionId
     * @return
     *     returns com.coverity.ws.v7.AttributeDefinitionDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttribute", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAttribute")
    @ResponseWrapper(localName = "getAttributeResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAttributeResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getAttributeRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getAttribute/Fault/CovRemoteServiceException")
    })
    public AttributeDefinitionDataObj getAttribute(
        @WebParam(name = "attributeDefinitionId", targetNamespace = "")
        AttributeDefinitionIdDataObj attributeDefinitionId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v7.VersionDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetVersionResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getVersionRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getVersionResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getVersion/Fault/CovRemoteServiceException")
    })
    public VersionDataObj getVersion()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v7.GroupsPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroups", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetGroups")
    @ResponseWrapper(localName = "getGroupsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetGroupsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getGroupsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getGroupsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getGroups/Fault/CovRemoteServiceException")
    })
    public GroupsPageDataObj getGroups(
        @WebParam(name = "filterSpec", targetNamespace = "")
        GroupFilterSpecDataObj filterSpec,
        @WebParam(name = "pageSpec", targetNamespace = "")
        PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v7.UsersPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetUsersResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getUsersRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getUsersResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getUsers/Fault/CovRemoteServiceException")
    })
    public UsersPageDataObj getUsers(
        @WebParam(name = "filterSpec", targetNamespace = "")
        UserFilterSpecDataObj filterSpec,
        @WebParam(name = "pageSpec", targetNamespace = "")
        PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns com.coverity.ws.v7.GroupDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroup", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetGroup")
    @ResponseWrapper(localName = "getGroupResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetGroupResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getGroupRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getGroup/Fault/CovRemoteServiceException")
    })
    public GroupDataObj getGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        GroupIdDataObj groupId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleId
     * @return
     *     returns com.coverity.ws.v7.RoleDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRole", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetRole")
    @ResponseWrapper(localName = "getRoleResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetRoleResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getRoleRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getRole/Fault/CovRemoteServiceException")
    })
    public RoleDataObj getRole(
        @WebParam(name = "roleId", targetNamespace = "")
        RoleIdDataObj roleId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createAttribute", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateAttribute")
    @ResponseWrapper(localName = "createAttributeResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateAttributeResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/createAttributeRequest", output = "http://ws.coverity.com/v7/ConfigurationService/createAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/createAttribute/Fault/CovRemoteServiceException")
    })
    public void createAttribute(
        @WebParam(name = "attributeDefinitionSpec", targetNamespace = "")
        AttributeDefinitionSpecDataObj attributeDefinitionSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v7.RoleDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRoles", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAllRoles")
    @ResponseWrapper(localName = "getAllRolesResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAllRolesResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getAllRolesRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getAllRolesResponse")
    public List<RoleDataObj> getAllRoles();

    /**
     * 
     * @param groupSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createGroup", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateGroup")
    @ResponseWrapper(localName = "createGroupResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateGroupResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/createGroupRequest", output = "http://ws.coverity.com/v7/ConfigurationService/createGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/createGroup/Fault/CovRemoteServiceException")
    })
    public void createGroup(
        @WebParam(name = "groupSpec", targetNamespace = "")
        GroupSpecDataObj groupSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createRole", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateRole")
    @ResponseWrapper(localName = "createRoleResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateRoleResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/createRoleRequest", output = "http://ws.coverity.com/v7/ConfigurationService/createRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/createRole/Fault/CovRemoteServiceException")
    })
    public void createRole(
        @WebParam(name = "roleSpec", targetNamespace = "")
        RoleSpecDataObj roleSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteGroup", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteGroup")
    @ResponseWrapper(localName = "deleteGroupResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteGroupResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/deleteGroupRequest", output = "http://ws.coverity.com/v7/ConfigurationService/deleteGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/deleteGroup/Fault/CovRemoteServiceException")
    })
    public void deleteGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        GroupIdDataObj groupId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupSpec
     * @param groupId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateGroup", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateGroup")
    @ResponseWrapper(localName = "updateGroupResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateGroupResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/updateGroupRequest", output = "http://ws.coverity.com/v7/ConfigurationService/updateGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/updateGroup/Fault/CovRemoteServiceException")
    })
    public void updateGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        GroupIdDataObj groupId,
        @WebParam(name = "groupSpec", targetNamespace = "")
        GroupSpecDataObj groupSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleSpec
     * @param roleId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateRole", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateRole")
    @ResponseWrapper(localName = "updateRoleResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateRoleResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/updateRoleRequest", output = "http://ws.coverity.com/v7/ConfigurationService/updateRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/updateRole/Fault/CovRemoteServiceException")
    })
    public void updateRole(
        @WebParam(name = "roleId", targetNamespace = "")
        RoleIdDataObj roleId,
        @WebParam(name = "roleSpec", targetNamespace = "")
        RoleSpecDataObj roleSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRole", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteRole")
    @ResponseWrapper(localName = "deleteRoleResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteRoleResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/deleteRoleRequest", output = "http://ws.coverity.com/v7/ConfigurationService/deleteRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/deleteRole/Fault/CovRemoteServiceException")
    })
    public void deleteRole(
        @WebParam(name = "roleId", targetNamespace = "")
        RoleIdDataObj roleId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createStream", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateStream")
    @ResponseWrapper(localName = "createStreamResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateStreamResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/createStreamRequest", output = "http://ws.coverity.com/v7/ConfigurationService/createStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/createStream/Fault/CovRemoteServiceException")
    })
    public void createStream(
        @WebParam(name = "streamSpec", targetNamespace = "")
        StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param streamSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateStream", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateStream")
    @ResponseWrapper(localName = "updateStreamResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateStreamResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/updateStreamRequest", output = "http://ws.coverity.com/v7/ConfigurationService/updateStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/updateStream/Fault/CovRemoteServiceException")
    })
    public void updateStream(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "streamSpec", targetNamespace = "")
        StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param onlyIfEmpty
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStream", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteStream")
    @ResponseWrapper(localName = "deleteStreamResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteStreamResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/deleteStreamRequest", output = "http://ws.coverity.com/v7/ConfigurationService/deleteStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/deleteStream/Fault/CovRemoteServiceException")
    })
    public void deleteStream(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "onlyIfEmpty", targetNamespace = "")
        boolean onlyIfEmpty)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param userSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateUserResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/createUserRequest", output = "http://ws.coverity.com/v7/ConfigurationService/createUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/createUser/Fault/CovRemoteServiceException")
    })
    public void createUser(
        @WebParam(name = "userSpec", targetNamespace = "")
        UserSpecDataObj userSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @param userSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateUserResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/updateUserRequest", output = "http://ws.coverity.com/v7/ConfigurationService/updateUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/updateUser/Fault/CovRemoteServiceException")
    })
    public void updateUser(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "userSpec", targetNamespace = "")
        UserSpecDataObj userSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteUserResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/deleteUserRequest", output = "http://ws.coverity.com/v7/ConfigurationService/deleteUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/deleteUser/Fault/CovRemoteServiceException")
    })
    public void deleteUser(
        @WebParam(name = "username", targetNamespace = "")
        String username)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @return
     *     returns java.util.List<com.coverity.ws.v7.PermissionDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllIntegrityControlPermissions", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAllIntegrityControlPermissions")
    @ResponseWrapper(localName = "getAllIntegrityControlPermissionsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAllIntegrityControlPermissionsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getAllIntegrityControlPermissionsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getAllIntegrityControlPermissionsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getAllIntegrityControlPermissions/Fault/CovRemoteServiceException")
    })
    public List<PermissionDataObj> getAllIntegrityControlPermissions(
        @WebParam(name = "username", targetNamespace = "")
        String username)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionId
     * @param attributeDefinitionSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateAttribute", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateAttribute")
    @ResponseWrapper(localName = "updateAttributeResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateAttributeResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/updateAttributeRequest", output = "http://ws.coverity.com/v7/ConfigurationService/updateAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/updateAttribute/Fault/CovRemoteServiceException")
    })
    public void updateAttribute(
        @WebParam(name = "attributeDefinitionId", targetNamespace = "")
        AttributeDefinitionIdDataObj attributeDefinitionId,
        @WebParam(name = "attributeDefinitionSpec", targetNamespace = "")
        AttributeDefinitionSpecDataObj attributeDefinitionSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAttribute", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteAttribute")
    @ResponseWrapper(localName = "deleteAttributeResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteAttributeResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/deleteAttributeRequest", output = "http://ws.coverity.com/v7/ConfigurationService/deleteAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/deleteAttribute/Fault/CovRemoteServiceException")
    })
    public void deleteAttribute(
        @WebParam(name = "attributeDefinitionId", targetNamespace = "")
        AttributeDefinitionIdDataObj attributeDefinitionId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createComponentMap", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateComponentMap")
    @ResponseWrapper(localName = "createComponentMapResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/createComponentMapRequest", output = "http://ws.coverity.com/v7/ConfigurationService/createComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/createComponentMap/Fault/CovRemoteServiceException")
    })
    public void createComponentMap(
        @WebParam(name = "componentMapSpec", targetNamespace = "")
        ComponentMapSpecDataObj componentMapSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapSpec
     * @param componentMapId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateComponentMap", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateComponentMap")
    @ResponseWrapper(localName = "updateComponentMapResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/updateComponentMapRequest", output = "http://ws.coverity.com/v7/ConfigurationService/updateComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/updateComponentMap/Fault/CovRemoteServiceException")
    })
    public void updateComponentMap(
        @WebParam(name = "componentMapId", targetNamespace = "")
        ComponentMapIdDataObj componentMapId,
        @WebParam(name = "componentMapSpec", targetNamespace = "")
        ComponentMapSpecDataObj componentMapSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteComponentMap", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteComponentMap")
    @ResponseWrapper(localName = "deleteComponentMapResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/deleteComponentMapRequest", output = "http://ws.coverity.com/v7/ConfigurationService/deleteComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/deleteComponentMap/Fault/CovRemoteServiceException")
    })
    public void deleteComponentMap(
        @WebParam(name = "componentMapId", targetNamespace = "")
        ComponentMapIdDataObj componentMapId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createProject", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateProjectResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/createProjectRequest", output = "http://ws.coverity.com/v7/ConfigurationService/createProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/createProject/Fault/CovRemoteServiceException")
    })
    public void createProject(
        @WebParam(name = "projectSpec", targetNamespace = "")
        ProjectSpecDataObj projectSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectSpec
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateProjectResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/updateProjectRequest", output = "http://ws.coverity.com/v7/ConfigurationService/updateProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/updateProject/Fault/CovRemoteServiceException")
    })
    public void updateProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "projectSpec", targetNamespace = "")
        ProjectSpecDataObj projectSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProject", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteProject")
    @ResponseWrapper(localName = "deleteProjectResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteProjectResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/deleteProjectRequest", output = "http://ws.coverity.com/v7/ConfigurationService/deleteProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/deleteProject/Fault/CovRemoteServiceException")
    })
    public void deleteProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createTriageStore", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateTriageStore")
    @ResponseWrapper(localName = "createTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/createTriageStoreRequest", output = "http://ws.coverity.com/v7/ConfigurationService/createTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/createTriageStore/Fault/CovRemoteServiceException")
    })
    public void createTriageStore(
        @WebParam(name = "triageStoreSpec", targetNamespace = "")
        TriageStoreSpecDataObj triageStoreSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreSpec
     * @param triageStoreId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateTriageStore", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateTriageStore")
    @ResponseWrapper(localName = "updateTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/updateTriageStoreRequest", output = "http://ws.coverity.com/v7/ConfigurationService/updateTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/updateTriageStore/Fault/CovRemoteServiceException")
    })
    public void updateTriageStore(
        @WebParam(name = "triageStoreId", targetNamespace = "")
        TriageStoreIdDataObj triageStoreId,
        @WebParam(name = "triageStoreSpec", targetNamespace = "")
        TriageStoreSpecDataObj triageStoreSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTriageStore", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteTriageStore")
    @ResponseWrapper(localName = "deleteTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/deleteTriageStoreRequest", output = "http://ws.coverity.com/v7/ConfigurationService/deleteTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/deleteTriageStore/Fault/CovRemoteServiceException")
    })
    public void deleteTriageStore(
        @WebParam(name = "triageStoreId", targetNamespace = "")
        TriageStoreIdDataObj triageStoreId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentId
     * @return
     *     returns com.coverity.ws.v7.ComponentDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponent", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetComponent")
    @ResponseWrapper(localName = "getComponentResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetComponentResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getComponentRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getComponentResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getComponent/Fault/CovRemoteServiceException")
    })
    public ComponentDataObj getComponent(
        @WebParam(name = "componentId", targetNamespace = "")
        ComponentIdDataObj componentId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @return
     *     returns com.coverity.ws.v7.UserDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetUserResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getUserRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getUser/Fault/CovRemoteServiceException")
    })
    public UserDataObj getUser(
        @WebParam(name = "username", targetNamespace = "")
        String username)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v7.StreamDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStreams", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetStreams")
    @ResponseWrapper(localName = "getStreamsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetStreamsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getStreamsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getStreamsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getStreams/Fault/CovRemoteServiceException")
    })
    public List<StreamDataObj> getStreams(
        @WebParam(name = "filterSpec", targetNamespace = "")
        StreamFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v7.CheckerPropertyDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCheckerProperties", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetCheckerProperties")
    @ResponseWrapper(localName = "getCheckerPropertiesResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetCheckerPropertiesResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getCheckerPropertiesRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getCheckerPropertiesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getCheckerProperties/Fault/CovRemoteServiceException")
    })
    public List<CheckerPropertyDataObj> getCheckerProperties(
        @WebParam(name = "filterSpec", targetNamespace = "")
        CheckerPropertyFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSnapshot", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteSnapshot")
    @ResponseWrapper(localName = "deleteSnapshotResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteSnapshotResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/deleteSnapshotRequest", output = "http://ws.coverity.com/v7/ConfigurationService/deleteSnapshotResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/deleteSnapshot/Fault/CovRemoteServiceException")
    })
    public void deleteSnapshot(
        @WebParam(name = "snapshotId", targetNamespace = "")
        List<SnapshotIdDataObj> snapshotId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param viewname
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "executeNotification", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.ExecuteNotification")
    @ResponseWrapper(localName = "executeNotificationResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.ExecuteNotificationResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/executeNotificationRequest", output = "http://ws.coverity.com/v7/ConfigurationService/executeNotificationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/executeNotification/Fault/CovRemoteServiceException")
    })
    public void executeNotification(
        @WebParam(name = "viewname", targetNamespace = "")
        String viewname)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v7.ProjectDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProjects", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetProjects")
    @ResponseWrapper(localName = "getProjectsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetProjectsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getProjectsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getProjectsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getProjects/Fault/CovRemoteServiceException")
    })
    public List<ProjectDataObj> getProjects(
        @WebParam(name = "filterSpec", targetNamespace = "")
        ProjectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @param sourceStreamId
     * @return
     *     returns com.coverity.ws.v7.StreamDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "copyStream", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CopyStream")
    @ResponseWrapper(localName = "copyStreamResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CopyStreamResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/copyStreamRequest", output = "http://ws.coverity.com/v7/ConfigurationService/copyStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/copyStream/Fault/CovRemoteServiceException")
    })
    public StreamDataObj copyStream(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "sourceStreamId", targetNamespace = "")
        StreamIdDataObj sourceStreamId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamSpec
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createStreamInProject", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateStreamInProject")
    @ResponseWrapper(localName = "createStreamInProjectResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateStreamInProjectResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/createStreamInProjectRequest", output = "http://ws.coverity.com/v7/ConfigurationService/createStreamInProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/createStreamInProject/Fault/CovRemoteServiceException")
    })
    public void createStreamInProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "streamSpec", targetNamespace = "")
        StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setAcceptingNewCommits", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.SetAcceptingNewCommits")
    @ResponseWrapper(localName = "setAcceptingNewCommitsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.SetAcceptingNewCommitsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/setAcceptingNewCommitsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/setAcceptingNewCommitsResponse")
    public void setAcceptingNewCommits(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessageOfTheDay", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetMessageOfTheDay")
    @ResponseWrapper(localName = "getMessageOfTheDayResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetMessageOfTheDayResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getMessageOfTheDayRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getMessageOfTheDayResponse")
    public String getMessageOfTheDay();

    /**
     * 
     * @param message
     */
    @WebMethod
    @RequestWrapper(localName = "setMessageOfTheDay", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.SetMessageOfTheDay")
    @ResponseWrapper(localName = "setMessageOfTheDayResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.SetMessageOfTheDayResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/setMessageOfTheDayRequest", output = "http://ws.coverity.com/v7/ConfigurationService/setMessageOfTheDayResponse")
    public void setMessageOfTheDay(
        @WebParam(name = "message", targetNamespace = "")
        String message);

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v7.TriageStoreDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTriageStores", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetTriageStores")
    @ResponseWrapper(localName = "getTriageStoresResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetTriageStoresResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getTriageStoresRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getTriageStoresResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getTriageStores/Fault/CovRemoteServiceException")
    })
    public List<TriageStoreDataObj> getTriageStores(
        @WebParam(name = "filterSpec", targetNamespace = "")
        TriageStoreFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v7.CommitStateDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommitState", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetCommitState")
    @ResponseWrapper(localName = "getCommitStateResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetCommitStateResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getCommitStateRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getCommitStateResponse")
    public CommitStateDataObj getCommitState();

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v7.ServerDomainIdDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLdapServerDomains", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetLdapServerDomains")
    @ResponseWrapper(localName = "getLdapServerDomainsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetLdapServerDomainsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getLdapServerDomainsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getLdapServerDomainsResponse")
    public List<ServerDomainIdDataObj> getLdapServerDomains();

    /**
     * 
     * @return
     *     returns com.coverity.ws.v7.LicenseStateDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLicenseState", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetLicenseState")
    @ResponseWrapper(localName = "getLicenseStateResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetLicenseStateResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getLicenseStateRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getLicenseStateResponse")
    public LicenseStateDataObj getLicenseState();

    /**
     * 
     * @param snapshotId
     * @param snapshotData
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateSnapshotInfo", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateSnapshotInfo")
    @ResponseWrapper(localName = "updateSnapshotInfoResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateSnapshotInfoResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/updateSnapshotInfoRequest", output = "http://ws.coverity.com/v7/ConfigurationService/updateSnapshotInfoResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/updateSnapshotInfo/Fault/CovRemoteServiceException")
    })
    public void updateSnapshotInfo(
        @WebParam(name = "snapshotId", targetNamespace = "")
        SnapshotIdDataObj snapshotId,
        @WebParam(name = "snapshotData", targetNamespace = "")
        SnapshotInfoDataObj snapshotData)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v7.FeatureUpdateTimeDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastUpdateTimes", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetLastUpdateTimes")
    @ResponseWrapper(localName = "getLastUpdateTimesResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetLastUpdateTimesResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getLastUpdateTimesRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getLastUpdateTimesResponse")
    public List<FeatureUpdateTimeDataObj> getLastUpdateTimes();

    /**
     * 
     * @param ldapConfigurationSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createLdapConfiguration", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateLdapConfiguration")
    @ResponseWrapper(localName = "createLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.CreateLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/createLdapConfigurationRequest", output = "http://ws.coverity.com/v7/ConfigurationService/createLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/createLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void createLdapConfiguration(
        @WebParam(name = "ldapConfigurationSpec", targetNamespace = "")
        LdapConfigurationSpecDataObj ldapConfigurationSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param ldapConfigurationSpec
     * @param serverDomainIdDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateLdapConfiguration", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateLdapConfiguration")
    @ResponseWrapper(localName = "updateLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.UpdateLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/updateLdapConfigurationRequest", output = "http://ws.coverity.com/v7/ConfigurationService/updateLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/updateLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void updateLdapConfiguration(
        @WebParam(name = "serverDomainIdDataObj", targetNamespace = "")
        ServerDomainIdDataObj serverDomainIdDataObj,
        @WebParam(name = "ldapConfigurationSpec", targetNamespace = "")
        LdapConfigurationSpecDataObj ldapConfigurationSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v7.SnapshotPurgeDetailsObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotPurgeDetails", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetSnapshotPurgeDetails")
    @ResponseWrapper(localName = "getSnapshotPurgeDetailsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetSnapshotPurgeDetailsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getSnapshotPurgeDetailsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getSnapshotPurgeDetailsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getSnapshotPurgeDetails/Fault/CovRemoteServiceException")
    })
    public SnapshotPurgeDetailsObj getSnapshotPurgeDetails()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param purgeDetailsSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setSnapshotPurgeDetails", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.SetSnapshotPurgeDetails")
    @ResponseWrapper(localName = "setSnapshotPurgeDetailsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.SetSnapshotPurgeDetailsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/setSnapshotPurgeDetailsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/setSnapshotPurgeDetailsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/setSnapshotPurgeDetails/Fault/CovRemoteServiceException")
    })
    public void setSnapshotPurgeDetails(
        @WebParam(name = "purgeDetailsSpec", targetNamespace = "")
        SnapshotPurgeDetailsObj purgeDetailsSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param srcTriageStoreIds
     * @param triageStoreId
     * @param deleteSourceStores
     * @param assignStreamsToTargetStore
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "mergeTriageStores", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.MergeTriageStores")
    @ResponseWrapper(localName = "mergeTriageStoresResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.MergeTriageStoresResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/mergeTriageStoresRequest", output = "http://ws.coverity.com/v7/ConfigurationService/mergeTriageStoresResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/mergeTriageStores/Fault/CovRemoteServiceException")
    })
    public void mergeTriageStores(
        @WebParam(name = "srcTriageStoreIds", targetNamespace = "")
        List<TriageStoreIdDataObj> srcTriageStoreIds,
        @WebParam(name = "triageStoreId", targetNamespace = "")
        TriageStoreIdDataObj triageStoreId,
        @WebParam(name = "deleteSourceStores", targetNamespace = "")
        boolean deleteSourceStores,
        @WebParam(name = "assignStreamsToTargetStore", targetNamespace = "")
        boolean assignStreamsToTargetStore)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v7.PermissionDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPermissions", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAllPermissions")
    @ResponseWrapper(localName = "getAllPermissionsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAllPermissionsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getAllPermissionsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getAllPermissionsResponse")
    public List<PermissionDataObj> getAllPermissions();

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v7.LdapConfigurationDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLdapConfigurations", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAllLdapConfigurations")
    @ResponseWrapper(localName = "getAllLdapConfigurationsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetAllLdapConfigurationsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getAllLdapConfigurationsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getAllLdapConfigurationsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getAllLdapConfigurations/Fault/CovRemoteServiceException")
    })
    public List<LdapConfigurationDataObj> getAllLdapConfigurations()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @return
     *     returns java.util.List<com.coverity.ws.v7.DeleteSnapshotJobInfoDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeleteSnapshotJobInfo", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetDeleteSnapshotJobInfo")
    @ResponseWrapper(localName = "getDeleteSnapshotJobInfoResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetDeleteSnapshotJobInfoResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getDeleteSnapshotJobInfoRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getDeleteSnapshotJobInfoResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getDeleteSnapshotJobInfo/Fault/CovRemoteServiceException")
    })
    public List<DeleteSnapshotJobInfoDataObj> getDeleteSnapshotJobInfo(
        @WebParam(name = "snapshotId", targetNamespace = "")
        List<SnapshotIdDataObj> snapshotId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v7.SnapshotIdDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotsForStream", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetSnapshotsForStream")
    @ResponseWrapper(localName = "getSnapshotsForStreamResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetSnapshotsForStreamResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getSnapshotsForStreamRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getSnapshotsForStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getSnapshotsForStream/Fault/CovRemoteServiceException")
    })
    public List<SnapshotIdDataObj> getSnapshotsForStream(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "filterSpec", targetNamespace = "")
        SnapshotFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param serverDomainIdDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteLdapConfiguration", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteLdapConfiguration")
    @ResponseWrapper(localName = "deleteLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.DeleteLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/deleteLdapConfigurationRequest", output = "http://ws.coverity.com/v7/ConfigurationService/deleteLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/deleteLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void deleteLdapConfiguration(
        @WebParam(name = "serverDomainIdDataObj", targetNamespace = "")
        ServerDomainIdDataObj serverDomainIdDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v7.ComponentMapDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponentMaps", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetComponentMaps")
    @ResponseWrapper(localName = "getComponentMapsResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetComponentMapsResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getComponentMapsRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getComponentMapsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getComponentMaps/Fault/CovRemoteServiceException")
    })
    public List<ComponentMapDataObj> getComponentMaps(
        @WebParam(name = "filterSpec", targetNamespace = "")
        ComponentMapFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDefectStatuses", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetDefectStatuses")
    @ResponseWrapper(localName = "getDefectStatusesResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetDefectStatusesResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getDefectStatusesRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getDefectStatusesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getDefectStatuses/Fault/CovRemoteServiceException")
    })
    public List<String> getDefectStatuses()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotIds
     * @return
     *     returns java.util.List<com.coverity.ws.v7.SnapshotInfoDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotInformation", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetSnapshotInformation")
    @ResponseWrapper(localName = "getSnapshotInformationResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetSnapshotInformationResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getSnapshotInformationRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getSnapshotInformationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getSnapshotInformation/Fault/CovRemoteServiceException")
    })
    public List<SnapshotInfoDataObj> getSnapshotInformation(
        @WebParam(name = "snapshotIds", targetNamespace = "")
        List<SnapshotIdDataObj> snapshotIds)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerTime", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetServerTime")
    @ResponseWrapper(localName = "getServerTimeResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetServerTimeResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getServerTimeRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getServerTimeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v7/ConfigurationService/getServerTime/Fault/CovRemoteServiceException")
    })
    public XMLGregorianCalendar getServerTime()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v7.ConfigurationDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSystemConfig", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetSystemConfig")
    @ResponseWrapper(localName = "getSystemConfigResponse", targetNamespace = "http://ws.coverity.com/v7", className = "com.coverity.ws.v7.GetSystemConfigResponse")
    @Action(input = "http://ws.coverity.com/v7/ConfigurationService/getSystemConfigRequest", output = "http://ws.coverity.com/v7/ConfigurationService/getSystemConfigResponse")
    public ConfigurationDataObj getSystemConfig();

}
