
package com.coverity.ws.v8;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConfigurationService", targetNamespace = "http://ws.coverity.com/v8")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConfigurationService {


    /**
     * 
     * @param message
     * @param usernames
     * @param subject
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "notify", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.Notify")
    @ResponseWrapper(localName = "notifyResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.NotifyResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/notifyRequest", output = "http://ws.coverity.com/v8/ConfigurationService/notifyResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/notify/Fault/CovRemoteServiceException")
    })
    public List<String> notify(
        @WebParam(name = "usernames", targetNamespace = "")
        List<String> usernames,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "message", targetNamespace = "")
        String message)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v8.AttributeDefinitionDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttributes", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetAttributes")
    @ResponseWrapper(localName = "getAttributesResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetAttributesResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getAttributesRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getAttributesResponse")
    public List<AttributeDefinitionDataObj> getAttributes();

    /**
     * 
     * @param attributeDefinitionId
     * @return
     *     returns com.coverity.ws.v8.AttributeDefinitionDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttribute", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetAttribute")
    @ResponseWrapper(localName = "getAttributeResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetAttributeResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getAttributeRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getAttribute/Fault/CovRemoteServiceException")
    })
    public AttributeDefinitionDataObj getAttribute(
        @WebParam(name = "attributeDefinitionId", targetNamespace = "")
        AttributeDefinitionIdDataObj attributeDefinitionId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v8.VersionDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetVersionResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getVersionRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getVersionResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getVersion/Fault/CovRemoteServiceException")
    })
    public VersionDataObj getVersion()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v8.GroupsPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroups", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetGroups")
    @ResponseWrapper(localName = "getGroupsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetGroupsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getGroupsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getGroupsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getGroups/Fault/CovRemoteServiceException")
    })
    public GroupsPageDataObj getGroups(
        @WebParam(name = "filterSpec", targetNamespace = "")
        GroupFilterSpecDataObj filterSpec,
        @WebParam(name = "pageSpec", targetNamespace = "")
        PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @param pageSpec
     * @return
     *     returns com.coverity.ws.v8.UsersPageDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetUsersResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getUsersRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getUsersResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getUsers/Fault/CovRemoteServiceException")
    })
    public UsersPageDataObj getUsers(
        @WebParam(name = "filterSpec", targetNamespace = "")
        UserFilterSpecDataObj filterSpec,
        @WebParam(name = "pageSpec", targetNamespace = "")
        PageSpecDataObj pageSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupId
     * @return
     *     returns com.coverity.ws.v8.GroupDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroup", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetGroup")
    @ResponseWrapper(localName = "getGroupResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetGroupResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getGroupRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getGroup/Fault/CovRemoteServiceException")
    })
    public GroupDataObj getGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        GroupIdDataObj groupId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleId
     * @return
     *     returns com.coverity.ws.v8.RoleDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRole", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetRole")
    @ResponseWrapper(localName = "getRoleResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetRoleResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getRoleRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getRole/Fault/CovRemoteServiceException")
    })
    public RoleDataObj getRole(
        @WebParam(name = "roleId", targetNamespace = "")
        RoleIdDataObj roleId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createAttribute", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateAttribute")
    @ResponseWrapper(localName = "createAttributeResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateAttributeResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/createAttributeRequest", output = "http://ws.coverity.com/v8/ConfigurationService/createAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/createAttribute/Fault/CovRemoteServiceException")
    })
    public void createAttribute(
        @WebParam(name = "attributeDefinitionSpec", targetNamespace = "")
        AttributeDefinitionSpecDataObj attributeDefinitionSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v8.RoleDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRoles", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetAllRoles")
    @ResponseWrapper(localName = "getAllRolesResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetAllRolesResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getAllRolesRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getAllRolesResponse")
    public List<RoleDataObj> getAllRoles();

    /**
     * 
     * @param groupSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createGroup", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateGroup")
    @ResponseWrapper(localName = "createGroupResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateGroupResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/createGroupRequest", output = "http://ws.coverity.com/v8/ConfigurationService/createGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/createGroup/Fault/CovRemoteServiceException")
    })
    public void createGroup(
        @WebParam(name = "groupSpec", targetNamespace = "")
        GroupSpecDataObj groupSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createRole", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateRole")
    @ResponseWrapper(localName = "createRoleResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateRoleResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/createRoleRequest", output = "http://ws.coverity.com/v8/ConfigurationService/createRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/createRole/Fault/CovRemoteServiceException")
    })
    public void createRole(
        @WebParam(name = "roleSpec", targetNamespace = "")
        RoleSpecDataObj roleSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteGroup", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteGroup")
    @ResponseWrapper(localName = "deleteGroupResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteGroupResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/deleteGroupRequest", output = "http://ws.coverity.com/v8/ConfigurationService/deleteGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/deleteGroup/Fault/CovRemoteServiceException")
    })
    public void deleteGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        GroupIdDataObj groupId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param groupSpec
     * @param groupId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateGroup", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateGroup")
    @ResponseWrapper(localName = "updateGroupResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateGroupResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateGroupRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateGroupResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateGroup/Fault/CovRemoteServiceException")
    })
    public void updateGroup(
        @WebParam(name = "groupId", targetNamespace = "")
        GroupIdDataObj groupId,
        @WebParam(name = "groupSpec", targetNamespace = "")
        GroupSpecDataObj groupSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleSpec
     * @param roleId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateRole", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateRole")
    @ResponseWrapper(localName = "updateRoleResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateRoleResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateRoleRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateRole/Fault/CovRemoteServiceException")
    })
    public void updateRole(
        @WebParam(name = "roleId", targetNamespace = "")
        RoleIdDataObj roleId,
        @WebParam(name = "roleSpec", targetNamespace = "")
        RoleSpecDataObj roleSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param roleId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRole", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteRole")
    @ResponseWrapper(localName = "deleteRoleResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteRoleResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/deleteRoleRequest", output = "http://ws.coverity.com/v8/ConfigurationService/deleteRoleResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/deleteRole/Fault/CovRemoteServiceException")
    })
    public void deleteRole(
        @WebParam(name = "roleId", targetNamespace = "")
        RoleIdDataObj roleId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createStream", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateStream")
    @ResponseWrapper(localName = "createStreamResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateStreamResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/createStreamRequest", output = "http://ws.coverity.com/v8/ConfigurationService/createStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/createStream/Fault/CovRemoteServiceException")
    })
    public void createStream(
        @WebParam(name = "streamSpec", targetNamespace = "")
        StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param streamSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateStream", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateStream")
    @ResponseWrapper(localName = "updateStreamResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateStreamResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateStreamRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateStream/Fault/CovRemoteServiceException")
    })
    public void updateStream(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "streamSpec", targetNamespace = "")
        StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param onlyIfEmpty
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteStream", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteStream")
    @ResponseWrapper(localName = "deleteStreamResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteStreamResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/deleteStreamRequest", output = "http://ws.coverity.com/v8/ConfigurationService/deleteStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/deleteStream/Fault/CovRemoteServiceException")
    })
    public void deleteStream(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "onlyIfEmpty", targetNamespace = "")
        boolean onlyIfEmpty)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param userSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateUserResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/createUserRequest", output = "http://ws.coverity.com/v8/ConfigurationService/createUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/createUser/Fault/CovRemoteServiceException")
    })
    public void createUser(
        @WebParam(name = "userSpec", targetNamespace = "")
        UserSpecDataObj userSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @param userSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateUserResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateUserRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateUser/Fault/CovRemoteServiceException")
    })
    public void updateUser(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "userSpec", targetNamespace = "")
        UserSpecDataObj userSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteUserResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/deleteUserRequest", output = "http://ws.coverity.com/v8/ConfigurationService/deleteUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/deleteUser/Fault/CovRemoteServiceException")
    })
    public void deleteUser(
        @WebParam(name = "username", targetNamespace = "")
        String username)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v8.SkeletonizationConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSkeletonizationConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSkeletonizationConfiguration")
    @ResponseWrapper(localName = "getSkeletonizationConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSkeletonizationConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getSkeletonizationConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getSkeletonizationConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getSkeletonizationConfiguration/Fault/CovRemoteServiceException")
    })
    public SkeletonizationConfigurationDataObj getSkeletonizationConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param skeletonizationConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setSkeletonizationConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetSkeletonizationConfiguration")
    @ResponseWrapper(localName = "setSkeletonizationConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetSkeletonizationConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/setSkeletonizationConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/setSkeletonizationConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/setSkeletonizationConfiguration/Fault/CovRemoteServiceException")
    })
    public void setSkeletonizationConfiguration(
        @WebParam(name = "skeletonizationConfigurationDataObj", targetNamespace = "")
        SkeletonizationConfigurationDataObj skeletonizationConfigurationDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionId
     * @param attributeDefinitionSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateAttribute", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateAttribute")
    @ResponseWrapper(localName = "updateAttributeResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateAttributeResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateAttributeRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateAttribute/Fault/CovRemoteServiceException")
    })
    public void updateAttribute(
        @WebParam(name = "attributeDefinitionId", targetNamespace = "")
        AttributeDefinitionIdDataObj attributeDefinitionId,
        @WebParam(name = "attributeDefinitionSpec", targetNamespace = "")
        AttributeDefinitionSpecDataObj attributeDefinitionSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param attributeDefinitionId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAttribute", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteAttribute")
    @ResponseWrapper(localName = "deleteAttributeResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteAttributeResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/deleteAttributeRequest", output = "http://ws.coverity.com/v8/ConfigurationService/deleteAttributeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/deleteAttribute/Fault/CovRemoteServiceException")
    })
    public void deleteAttribute(
        @WebParam(name = "attributeDefinitionId", targetNamespace = "")
        AttributeDefinitionIdDataObj attributeDefinitionId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createComponentMap", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateComponentMap")
    @ResponseWrapper(localName = "createComponentMapResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/createComponentMapRequest", output = "http://ws.coverity.com/v8/ConfigurationService/createComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/createComponentMap/Fault/CovRemoteServiceException")
    })
    public void createComponentMap(
        @WebParam(name = "componentMapSpec", targetNamespace = "")
        ComponentMapSpecDataObj componentMapSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapSpec
     * @param componentMapId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateComponentMap", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateComponentMap")
    @ResponseWrapper(localName = "updateComponentMapResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateComponentMapRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateComponentMap/Fault/CovRemoteServiceException")
    })
    public void updateComponentMap(
        @WebParam(name = "componentMapId", targetNamespace = "")
        ComponentMapIdDataObj componentMapId,
        @WebParam(name = "componentMapSpec", targetNamespace = "")
        ComponentMapSpecDataObj componentMapSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentMapId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteComponentMap", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteComponentMap")
    @ResponseWrapper(localName = "deleteComponentMapResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteComponentMapResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/deleteComponentMapRequest", output = "http://ws.coverity.com/v8/ConfigurationService/deleteComponentMapResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/deleteComponentMap/Fault/CovRemoteServiceException")
    })
    public void deleteComponentMap(
        @WebParam(name = "componentMapId", targetNamespace = "")
        ComponentMapIdDataObj componentMapId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createProject", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateProjectResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/createProjectRequest", output = "http://ws.coverity.com/v8/ConfigurationService/createProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/createProject/Fault/CovRemoteServiceException")
    })
    public void createProject(
        @WebParam(name = "projectSpec", targetNamespace = "")
        ProjectSpecDataObj projectSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectSpec
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateProjectResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateProjectRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateProject/Fault/CovRemoteServiceException")
    })
    public void updateProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "projectSpec", targetNamespace = "")
        ProjectSpecDataObj projectSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProject", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteProject")
    @ResponseWrapper(localName = "deleteProjectResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteProjectResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/deleteProjectRequest", output = "http://ws.coverity.com/v8/ConfigurationService/deleteProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/deleteProject/Fault/CovRemoteServiceException")
    })
    public void deleteProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createTriageStore", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateTriageStore")
    @ResponseWrapper(localName = "createTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/createTriageStoreRequest", output = "http://ws.coverity.com/v8/ConfigurationService/createTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/createTriageStore/Fault/CovRemoteServiceException")
    })
    public void createTriageStore(
        @WebParam(name = "triageStoreSpec", targetNamespace = "")
        TriageStoreSpecDataObj triageStoreSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreSpec
     * @param triageStoreId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateTriageStore", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateTriageStore")
    @ResponseWrapper(localName = "updateTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateTriageStoreRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateTriageStore/Fault/CovRemoteServiceException")
    })
    public void updateTriageStore(
        @WebParam(name = "triageStoreId", targetNamespace = "")
        TriageStoreIdDataObj triageStoreId,
        @WebParam(name = "triageStoreSpec", targetNamespace = "")
        TriageStoreSpecDataObj triageStoreSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param triageStoreId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteTriageStore", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteTriageStore")
    @ResponseWrapper(localName = "deleteTriageStoreResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteTriageStoreResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/deleteTriageStoreRequest", output = "http://ws.coverity.com/v8/ConfigurationService/deleteTriageStoreResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/deleteTriageStore/Fault/CovRemoteServiceException")
    })
    public void deleteTriageStore(
        @WebParam(name = "triageStoreId", targetNamespace = "")
        TriageStoreIdDataObj triageStoreId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param componentId
     * @return
     *     returns com.coverity.ws.v8.ComponentDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponent", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetComponent")
    @ResponseWrapper(localName = "getComponentResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetComponentResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getComponentRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getComponentResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getComponent/Fault/CovRemoteServiceException")
    })
    public ComponentDataObj getComponent(
        @WebParam(name = "componentId", targetNamespace = "")
        ComponentIdDataObj componentId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param username
     * @return
     *     returns com.coverity.ws.v8.UserDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetUserResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getUserRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getUserResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getUser/Fault/CovRemoteServiceException")
    })
    public UserDataObj getUser(
        @WebParam(name = "username", targetNamespace = "")
        String username)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v8.StreamDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStreams", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetStreams")
    @ResponseWrapper(localName = "getStreamsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetStreamsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getStreamsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getStreamsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getStreams/Fault/CovRemoteServiceException")
    })
    public List<StreamDataObj> getStreams(
        @WebParam(name = "filterSpec", targetNamespace = "")
        StreamFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v8.CheckerPropertyDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCheckerProperties", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetCheckerProperties")
    @ResponseWrapper(localName = "getCheckerPropertiesResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetCheckerPropertiesResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getCheckerPropertiesRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getCheckerPropertiesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getCheckerProperties/Fault/CovRemoteServiceException")
    })
    public List<CheckerPropertyDataObj> getCheckerProperties(
        @WebParam(name = "filterSpec", targetNamespace = "")
        CheckerPropertyFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteSnapshot", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteSnapshot")
    @ResponseWrapper(localName = "deleteSnapshotResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteSnapshotResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/deleteSnapshotRequest", output = "http://ws.coverity.com/v8/ConfigurationService/deleteSnapshotResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/deleteSnapshot/Fault/CovRemoteServiceException")
    })
    public void deleteSnapshot(
        @WebParam(name = "snapshotId", targetNamespace = "")
        List<SnapshotIdDataObj> snapshotId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param viewname
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "executeNotification", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.ExecuteNotification")
    @ResponseWrapper(localName = "executeNotificationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.ExecuteNotificationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/executeNotificationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/executeNotificationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/executeNotification/Fault/CovRemoteServiceException")
    })
    public void executeNotification(
        @WebParam(name = "viewname", targetNamespace = "")
        String viewname)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v8.ProjectDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProjects", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetProjects")
    @ResponseWrapper(localName = "getProjectsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetProjectsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getProjectsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getProjectsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getProjects/Fault/CovRemoteServiceException")
    })
    public List<ProjectDataObj> getProjects(
        @WebParam(name = "filterSpec", targetNamespace = "")
        ProjectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param projectId
     * @param sourceStreamId
     * @return
     *     returns com.coverity.ws.v8.StreamDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "copyStream", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CopyStream")
    @ResponseWrapper(localName = "copyStreamResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CopyStreamResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/copyStreamRequest", output = "http://ws.coverity.com/v8/ConfigurationService/copyStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/copyStream/Fault/CovRemoteServiceException")
    })
    public StreamDataObj copyStream(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "sourceStreamId", targetNamespace = "")
        StreamIdDataObj sourceStreamId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamSpec
     * @param projectId
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createStreamInProject", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateStreamInProject")
    @ResponseWrapper(localName = "createStreamInProjectResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateStreamInProjectResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/createStreamInProjectRequest", output = "http://ws.coverity.com/v8/ConfigurationService/createStreamInProjectResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/createStreamInProject/Fault/CovRemoteServiceException")
    })
    public void createStreamInProject(
        @WebParam(name = "projectId", targetNamespace = "")
        ProjectIdDataObj projectId,
        @WebParam(name = "streamSpec", targetNamespace = "")
        StreamSpecDataObj streamSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param acceptNewCommits
     */
    @WebMethod
    @RequestWrapper(localName = "setAcceptingNewCommits", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetAcceptingNewCommits")
    @ResponseWrapper(localName = "setAcceptingNewCommitsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetAcceptingNewCommitsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/setAcceptingNewCommitsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/setAcceptingNewCommitsResponse")
    public void setAcceptingNewCommits(
        @WebParam(name = "acceptNewCommits", targetNamespace = "")
        boolean acceptNewCommits);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessageOfTheDay", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetMessageOfTheDay")
    @ResponseWrapper(localName = "getMessageOfTheDayResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetMessageOfTheDayResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getMessageOfTheDayRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getMessageOfTheDayResponse")
    public String getMessageOfTheDay();

    /**
     * 
     * @param message
     */
    @WebMethod
    @RequestWrapper(localName = "setMessageOfTheDay", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetMessageOfTheDay")
    @ResponseWrapper(localName = "setMessageOfTheDayResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetMessageOfTheDayResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/setMessageOfTheDayRequest", output = "http://ws.coverity.com/v8/ConfigurationService/setMessageOfTheDayResponse")
    public void setMessageOfTheDay(
        @WebParam(name = "message", targetNamespace = "")
        String message);

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v8.TriageStoreDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTriageStores", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetTriageStores")
    @ResponseWrapper(localName = "getTriageStoresResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetTriageStoresResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getTriageStoresRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getTriageStoresResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getTriageStores/Fault/CovRemoteServiceException")
    })
    public List<TriageStoreDataObj> getTriageStores(
        @WebParam(name = "filterSpec", targetNamespace = "")
        TriageStoreFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v8.CommitStateDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommitState", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetCommitState")
    @ResponseWrapper(localName = "getCommitStateResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetCommitStateResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getCommitStateRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getCommitStateResponse")
    public CommitStateDataObj getCommitState();

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v8.ServerDomainIdDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLdapServerDomains", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetLdapServerDomains")
    @ResponseWrapper(localName = "getLdapServerDomainsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetLdapServerDomainsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getLdapServerDomainsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getLdapServerDomainsResponse")
    public List<ServerDomainIdDataObj> getLdapServerDomains();

    /**
     * 
     * @return
     *     returns com.coverity.ws.v8.LicenseStateDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLicenseState", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetLicenseState")
    @ResponseWrapper(localName = "getLicenseStateResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetLicenseStateResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getLicenseStateRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getLicenseStateResponse")
    public LicenseStateDataObj getLicenseState();

    /**
     * 
     * @param snapshotId
     * @param snapshotData
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateSnapshotInfo", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateSnapshotInfo")
    @ResponseWrapper(localName = "updateSnapshotInfoResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateSnapshotInfoResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateSnapshotInfoRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateSnapshotInfoResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateSnapshotInfo/Fault/CovRemoteServiceException")
    })
    public void updateSnapshotInfo(
        @WebParam(name = "snapshotId", targetNamespace = "")
        SnapshotIdDataObj snapshotId,
        @WebParam(name = "snapshotData", targetNamespace = "")
        SnapshotInfoDataObj snapshotData)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v8.FeatureUpdateTimeDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastUpdateTimes", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetLastUpdateTimes")
    @ResponseWrapper(localName = "getLastUpdateTimesResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetLastUpdateTimesResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getLastUpdateTimesRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getLastUpdateTimesResponse")
    public List<FeatureUpdateTimeDataObj> getLastUpdateTimes();

    /**
     * 
     * @param ldapConfigurationSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createLdapConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateLdapConfiguration")
    @ResponseWrapper(localName = "createLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.CreateLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/createLdapConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/createLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/createLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void createLdapConfiguration(
        @WebParam(name = "ldapConfigurationSpec", targetNamespace = "")
        LdapConfigurationSpecDataObj ldapConfigurationSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param ldapConfigurationSpec
     * @param serverDomainIdDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateLdapConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateLdapConfiguration")
    @ResponseWrapper(localName = "updateLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateLdapConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void updateLdapConfiguration(
        @WebParam(name = "serverDomainIdDataObj", targetNamespace = "")
        ServerDomainIdDataObj serverDomainIdDataObj,
        @WebParam(name = "ldapConfigurationSpec", targetNamespace = "")
        LdapConfigurationSpecDataObj ldapConfigurationSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v8.SnapshotPurgeDetailsObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotPurgeDetails", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSnapshotPurgeDetails")
    @ResponseWrapper(localName = "getSnapshotPurgeDetailsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSnapshotPurgeDetailsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getSnapshotPurgeDetailsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getSnapshotPurgeDetailsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getSnapshotPurgeDetails/Fault/CovRemoteServiceException")
    })
    public SnapshotPurgeDetailsObj getSnapshotPurgeDetails()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param purgeDetailsSpec
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setSnapshotPurgeDetails", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetSnapshotPurgeDetails")
    @ResponseWrapper(localName = "setSnapshotPurgeDetailsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetSnapshotPurgeDetailsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/setSnapshotPurgeDetailsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/setSnapshotPurgeDetailsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/setSnapshotPurgeDetails/Fault/CovRemoteServiceException")
    })
    public void setSnapshotPurgeDetails(
        @WebParam(name = "purgeDetailsSpec", targetNamespace = "")
        SnapshotPurgeDetailsObj purgeDetailsSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param backupConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setBackupConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetBackupConfiguration")
    @ResponseWrapper(localName = "setBackupConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetBackupConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/setBackupConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/setBackupConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/setBackupConfiguration/Fault/CovRemoteServiceException")
    })
    public void setBackupConfiguration(
        @WebParam(name = "backupConfigurationDataObj", targetNamespace = "")
        BackupConfigurationDataObj backupConfigurationDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v8.SignInSettingsDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSignInConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSignInConfiguration")
    @ResponseWrapper(localName = "getSignInConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSignInConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getSignInConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getSignInConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getSignInConfiguration/Fault/CovRemoteServiceException")
    })
    public SignInSettingsDataObj getSignInConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param signInSettingsDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateSignInConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateSignInConfiguration")
    @ResponseWrapper(localName = "updateSignInConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.UpdateSignInConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/updateSignInConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/updateSignInConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/updateSignInConfiguration/Fault/CovRemoteServiceException")
    })
    public void updateSignInConfiguration(
        @WebParam(name = "signInSettingsDataObj", targetNamespace = "")
        SignInSettingsDataObj signInSettingsDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v8.LicenseDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLicenseConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetLicenseConfiguration")
    @ResponseWrapper(localName = "getLicenseConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetLicenseConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getLicenseConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getLicenseConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getLicenseConfiguration/Fault/CovRemoteServiceException")
    })
    public LicenseDataObj getLicenseConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v8.ProjectDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeveloperStreamsProjects", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetDeveloperStreamsProjects")
    @ResponseWrapper(localName = "getDeveloperStreamsProjectsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetDeveloperStreamsProjectsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getDeveloperStreamsProjectsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getDeveloperStreamsProjectsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getDeveloperStreamsProjects/Fault/CovRemoteServiceException")
    })
    public List<ProjectDataObj> getDeveloperStreamsProjects(
        @WebParam(name = "filterSpec", targetNamespace = "")
        ProjectFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v8.BackupConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBackupConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetBackupConfiguration")
    @ResponseWrapper(localName = "getBackupConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetBackupConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getBackupConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getBackupConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getBackupConfiguration/Fault/CovRemoteServiceException")
    })
    public BackupConfigurationDataObj getBackupConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param loggingConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setLoggingConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetLoggingConfiguration")
    @ResponseWrapper(localName = "setLoggingConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.SetLoggingConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/setLoggingConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/setLoggingConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/setLoggingConfiguration/Fault/CovRemoteServiceException")
    })
    public void setLoggingConfiguration(
        @WebParam(name = "loggingConfigurationDataObj", targetNamespace = "")
        LoggingConfigurationDataObj loggingConfigurationDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v8.LoggingConfigurationDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoggingConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetLoggingConfiguration")
    @ResponseWrapper(localName = "getLoggingConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetLoggingConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getLoggingConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getLoggingConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getLoggingConfiguration/Fault/CovRemoteServiceException")
    })
    public LoggingConfigurationDataObj getLoggingConfiguration()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param licenseSpecDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "importLicense", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.ImportLicense")
    @ResponseWrapper(localName = "importLicenseResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.ImportLicenseResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/importLicenseRequest", output = "http://ws.coverity.com/v8/ConfigurationService/importLicenseResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/importLicense/Fault/CovRemoteServiceException")
    })
    public void importLicense(
        @WebParam(name = "licenseSpecDataObj", targetNamespace = "")
        LicenseSpecDataObj licenseSpecDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param srcTriageStoreIds
     * @param triageStoreId
     * @param deleteSourceStores
     * @param assignStreamsToTargetStore
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "mergeTriageStores", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.MergeTriageStores")
    @ResponseWrapper(localName = "mergeTriageStoresResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.MergeTriageStoresResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/mergeTriageStoresRequest", output = "http://ws.coverity.com/v8/ConfigurationService/mergeTriageStoresResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/mergeTriageStores/Fault/CovRemoteServiceException")
    })
    public void mergeTriageStores(
        @WebParam(name = "srcTriageStoreIds", targetNamespace = "")
        List<TriageStoreIdDataObj> srcTriageStoreIds,
        @WebParam(name = "triageStoreId", targetNamespace = "")
        TriageStoreIdDataObj triageStoreId,
        @WebParam(name = "deleteSourceStores", targetNamespace = "")
        boolean deleteSourceStores,
        @WebParam(name = "assignStreamsToTargetStore", targetNamespace = "")
        boolean assignStreamsToTargetStore)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v8.PermissionDataObj>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPermissions", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetAllPermissions")
    @ResponseWrapper(localName = "getAllPermissionsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetAllPermissionsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getAllPermissionsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getAllPermissionsResponse")
    public List<PermissionDataObj> getAllPermissions();

    /**
     * 
     * @return
     *     returns java.util.List<com.coverity.ws.v8.LdapConfigurationDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLdapConfigurations", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetAllLdapConfigurations")
    @ResponseWrapper(localName = "getAllLdapConfigurationsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetAllLdapConfigurationsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getAllLdapConfigurationsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getAllLdapConfigurationsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getAllLdapConfigurations/Fault/CovRemoteServiceException")
    })
    public List<LdapConfigurationDataObj> getAllLdapConfigurations()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotId
     * @return
     *     returns java.util.List<com.coverity.ws.v8.DeleteSnapshotJobInfoDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeleteSnapshotJobInfo", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetDeleteSnapshotJobInfo")
    @ResponseWrapper(localName = "getDeleteSnapshotJobInfoResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetDeleteSnapshotJobInfoResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getDeleteSnapshotJobInfoRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getDeleteSnapshotJobInfoResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getDeleteSnapshotJobInfo/Fault/CovRemoteServiceException")
    })
    public List<DeleteSnapshotJobInfoDataObj> getDeleteSnapshotJobInfo(
        @WebParam(name = "snapshotId", targetNamespace = "")
        List<SnapshotIdDataObj> snapshotId)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param streamId
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v8.SnapshotIdDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotsForStream", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSnapshotsForStream")
    @ResponseWrapper(localName = "getSnapshotsForStreamResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSnapshotsForStreamResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getSnapshotsForStreamRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getSnapshotsForStreamResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getSnapshotsForStream/Fault/CovRemoteServiceException")
    })
    public List<SnapshotIdDataObj> getSnapshotsForStream(
        @WebParam(name = "streamId", targetNamespace = "")
        StreamIdDataObj streamId,
        @WebParam(name = "filterSpec", targetNamespace = "")
        SnapshotFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param serverDomainIdDataObj
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteLdapConfiguration", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteLdapConfiguration")
    @ResponseWrapper(localName = "deleteLdapConfigurationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.DeleteLdapConfigurationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/deleteLdapConfigurationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/deleteLdapConfigurationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/deleteLdapConfiguration/Fault/CovRemoteServiceException")
    })
    public void deleteLdapConfiguration(
        @WebParam(name = "serverDomainIdDataObj", targetNamespace = "")
        ServerDomainIdDataObj serverDomainIdDataObj)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param filterSpec
     * @return
     *     returns java.util.List<com.coverity.ws.v8.ComponentMapDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponentMaps", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetComponentMaps")
    @ResponseWrapper(localName = "getComponentMapsResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetComponentMapsResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getComponentMapsRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getComponentMapsResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getComponentMaps/Fault/CovRemoteServiceException")
    })
    public List<ComponentMapDataObj> getComponentMaps(
        @WebParam(name = "filterSpec", targetNamespace = "")
        ComponentMapFilterSpecDataObj filterSpec)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDefectStatuses", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetDefectStatuses")
    @ResponseWrapper(localName = "getDefectStatusesResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetDefectStatusesResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getDefectStatusesRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getDefectStatusesResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getDefectStatuses/Fault/CovRemoteServiceException")
    })
    public List<String> getDefectStatuses()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @param snapshotIds
     * @return
     *     returns java.util.List<com.coverity.ws.v8.SnapshotInfoDataObj>
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnapshotInformation", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSnapshotInformation")
    @ResponseWrapper(localName = "getSnapshotInformationResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSnapshotInformationResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getSnapshotInformationRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getSnapshotInformationResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getSnapshotInformation/Fault/CovRemoteServiceException")
    })
    public List<SnapshotInfoDataObj> getSnapshotInformation(
        @WebParam(name = "snapshotIds", targetNamespace = "")
        List<SnapshotIdDataObj> snapshotIds)
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws CovRemoteServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerTime", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetServerTime")
    @ResponseWrapper(localName = "getServerTimeResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetServerTimeResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getServerTimeRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getServerTimeResponse", fault = {
        @FaultAction(className = CovRemoteServiceException_Exception.class, value = "http://ws.coverity.com/v8/ConfigurationService/getServerTime/Fault/CovRemoteServiceException")
    })
    public XMLGregorianCalendar getServerTime()
        throws CovRemoteServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.coverity.ws.v8.ConfigurationDataObj
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSystemConfig", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSystemConfig")
    @ResponseWrapper(localName = "getSystemConfigResponse", targetNamespace = "http://ws.coverity.com/v8", className = "com.coverity.ws.v8.GetSystemConfigResponse")
    @Action(input = "http://ws.coverity.com/v8/ConfigurationService/getSystemConfigRequest", output = "http://ws.coverity.com/v8/ConfigurationService/getSystemConfigResponse")
    public ConfigurationDataObj getSystemConfig();

}
